package RestOther;

public class ObjectDemo {
    int num;
    public ObjectDemo() {
        super();
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }
    //hashcode basically is random number generated by java to uniquely identify an object ,Two different objects having same number as parameter passed will have different hashcode

    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }

    @Override
    protected Object clone() throws CloneNotSupportedException {
        return super.clone();
    }

    @Override
    public String toString() {
        return super.toString();
    }




}
